"""
Generates a downloadable PDF summary of the QoE analysis - the EBITDA bridge,
adjustment detail, plain-English conclusion, and AI memo - styled simply and
cleanly so it's presentable as a real deliverable.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import io


def build_pdf_report(company_name: str, bridge: dict, conclusion: str, memo: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], fontSize=20,
                                  spaceAfter=4, textColor=colors.HexColor("#1A2332"))
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=10,
                                     textColor=colors.HexColor("#555555"), spaceAfter=18)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=13,
                                    spaceBefore=16, spaceAfter=8, textColor=colors.HexColor("#1A2332"))
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=15)
    conclusion_style = ParagraphStyle("Conclusion", parent=styles["Normal"], fontSize=11,
                                       leading=16, backColor=colors.HexColor("#F4F2ED"),
                                       borderPadding=10)

    elements = [
        Paragraph("Artha", title_style),
        Paragraph(f"AI-Powered Earnings Diligence — {company_name}", subtitle_style),
        Paragraph("The Bottom Line", heading_style),
        Paragraph(conclusion, conclusion_style),
        Spacer(1, 12),
        Paragraph("EBITDA Normalization Bridge", heading_style),
    ]

    table_data = [["Line Item", "Value (INR)"]]
    for step in bridge["bridge_steps"]:
        table_data.append([step["label"], f"{step['value']:,.0f}"])

    t = Table(table_data, colWidths=[10*cm, 6*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A2332")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F2ED")]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)

    if memo:
        elements.append(Paragraph("Quality of Earnings Memorandum", heading_style))
        for para in memo.split("\n"):
            if para.strip():
                elements.append(Paragraph(para, body_style))
                elements.append(Spacer(1, 6))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by Artha from publicly reported financial data. "
        "For illustrative purposes only; not investment or audit advice.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7,
                       textColor=colors.HexColor("#888888"))
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
